chore: Disable MSAL WithUnoHelpers for net6.0-macos
##[error]src\AddIns\Uno.UI.MSAL\AcquireTokenInteractiveParameterBuilderExtensions.cs(18,12): Error CS1061: 'AcquireTokenInteractiveParameterBuilder' does not contain a definition for 'WithParentActivityOrWindow' and no accessible extension method 'WithParentActivityOrWindow' accepting a first argument of type 'AcquireTokenInteractiveParameterBuilder' could be found (are you missing a using directive or an assembly reference?)